export const timezones = [
  { id: 1, name: 'International Date Line West', tz: 'Etc/GMT+12' },
  { id: 2, name: 'Coordinated Universal Time-11', tz: 'Etc/GMT+11' },
  { id: 3, name: 'Hawaii', tz: 'Pacific/Honolulu' },
  { id: 4, name: 'Alaska', tz: 'America/Anchorage' },
  { id: 5, name: 'Pacific Time (US & Canada)', tz: 'America/Los_Angeles' },
  { id: 6, name: 'Mountain Time (US & Canada)', tz: 'America/Denver' },
  { id: 7, name: 'Central Time (US & Canada)', tz: 'America/Chicago' },
  { id: 8, name: 'Eastern Time (US & Canada)', tz: 'America/New_York' },
  { id: 9, name: 'Atlantic Time (Canada)', tz: 'America/Halifax' },
  { id: 10, name: 'Greenwich Mean Time', tz: 'Etc/GMT' },
  { id: 11, name: 'Central European Time', tz: 'Europe/Berlin' },
  { id: 12, name: 'Eastern European Time', tz: 'Europe/Kiev' },
  { id: 13, name: 'Moscow Standard Time', tz: 'Europe/Moscow' },
  { id: 14, name: 'Gulf Standard Time', tz: 'Asia/Dubai' },
  { id: 15, name: 'Pakistan Standard Time', tz: 'Asia/Karachi' },
  { id: 16, name: 'India Standard Time', tz: 'Asia/Kolkata' },
  { id: 17, name: 'Bangladesh Standard Time', tz: 'Asia/Dhaka' },
  { id: 18, name: 'Indochina Time', tz: 'Asia/Bangkok' },
  { id: 19, name: 'China Standard Time', tz: 'Asia/Shanghai' },
  { id: 20, name: 'Japan Standard Time', tz: 'Asia/Tokyo' },
  { id: 21, name: 'Australian Eastern Time', tz: 'Australia/Sydney' },
  { id: 22, name: 'New Zealand Standard Time', tz: 'Pacific/Auckland' },
];
